# Generated by Django 5.1.6 on 2025-10-26 09:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0003_leave'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='time_applied',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='leave',
            name='date_applied',
            field=models.DateField(auto_now_add=True),
        ),
    ]
