# Generated by Django 5.1.6 on 2025-10-27 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0004_leave_time_applied_alter_leave_date_applied'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
